# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('operator', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('restor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restourant.Dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restourant.Order')),
            ],
        ),
    ]
