# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0002_order_orderdish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restourant.Dish'),
        ),
        migrations.DeleteModel(
            name='OrderDish',
        ),
    ]
